spring:
  datasource:
    url: "jdbc:h2:mem:test"
    driver-class-name: org.h2.Driver
    schema: public

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        hbm2ddl:
          auto: create

hibernate:
  dialect: "org.hibernate.dialect.H2Dialect"
  hbm2ddl:
    auto: create

server:
  port: 8092